complete -c backup --short h --long help --description 'Print help and exit'
complete -c backup --short v --long version --description 'Print version and exit'
complete -c backup --short g --long debug --description 'Run in debug mode with verbose logging'
complete -c backup --short i --long interactive --description 'Run interactively'
complete -c backup --short q --long quiet --description 'Run quietly'
complete -c backup --short V --long verbose --description 'Verbose logging'
complete -c backup --short a --long append --description 'Append todays date to the target backup directory'
complete -c backup --short D --long mkdir --description 'Bold text'
complete -c backup --short S --long swap --description 'Leave the backup in place, but move the original to destination'
complete -c backup --short d --long dest --description 'Backup files to this destination'
complete -c backup --short e --long ext --description 'File extension'
complete -c backup --short f --long format_datetime --description 'Date time format to use in the backup filename.'
complete -c backup --short s --long suffix --description 'Backup file suffix (datetime + extension)'
